#!/usr/bin/env python3
"""Append the above-fold subset of the runtime layer to the critical CSS files.

Extracted directly from the pv-sub.css runtime layer (single source of truth):
the global typography/overflow rules plus the complete mobile media blocks.
First paint then matches the final cascade exactly, so neither the LCP h1 nor
above-fold chrome (toc, faq summaries, breadcrumb bar) ever re-renders or
shifts when the full stylesheets arrive.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'assets/css/pv-sub.css'
LAYER_START = '/* === PV RUNTIME LAYER (formerly injected by pv-live.js) === */'
LAYER_END = '/* === END PV RUNTIME LAYER === */'
MARK_START = '/* === runtime-layer above-fold subset (generated by critical_runtime_subset.py) === */'
MARK_END = '/* === end runtime-layer subset === */'

GLOBAL_RULES = (
    'html,body{overflow-x:clip;max-width:100vw}',
    'html{scroll-padding-top:80px}',
    'html{hanging-punctuation:first allow-end last}',
    'h1,h2,h3,.section-title,.tier-name,.equal-paths-q{text-wrap:balance}',
    '.lead,.hero-sub,.body-section p,.tier-body,.manifesto p{text-wrap:pretty}',
    '.hero h1,.footer-brand,.section-title{text-box:trim-both cap alphabetic}',
    "@supports(padding:env(safe-area-inset-bottom)){.sticky-cta{padding-bottom:env(safe-area-inset-bottom)}body{padding-bottom:calc(62px + env(safe-area-inset-bottom))}}",
)


def extract_media_blocks(layer: str) -> str:
    """Pull the complete @media(max-width:...) blocks out of the runtime layer."""
    blocks = []
    for m in re.finditer(r'@media\(max-width:(?:760|440|360)px\)\{\n.*?\n\}', layer, re.S):
        blocks.append(m.group(0))
    if len(blocks) != 3:
        raise SystemExit(f'expected 3 mobile media blocks in runtime layer, found {len(blocks)}')
    return '\n'.join(blocks)


def build_subset() -> str:
    t = SRC.read_text(encoding='utf-8')
    m = re.search(re.escape(LAYER_START) + r'(.*?)' + re.escape(LAYER_END), t, re.S)
    if not m:
        raise SystemExit('runtime layer markers not found in pv-sub.css')
    layer = m.group(1)
    for rule in GLOBAL_RULES:
        if rule not in layer:
            raise SystemExit(f'global rule drifted out of runtime layer: {rule[:60]}')
    return '\n'.join(GLOBAL_RULES) + '\n' + extract_media_blocks(layer)


def patch(path: Path, subset: str) -> None:
    t = path.read_text(encoding='utf-8')
    for marker in (MARK_START, '/* === runtime-layer above-fold subset (keep in sync with pv-sub/pv-home runtime layer) === */'):
        t = re.sub(re.escape(marker) + r'.*?' + re.escape(MARK_END), '', t, flags=re.S)
    t = t.rstrip() + f'\n\n{MARK_START}\n{subset}\n{MARK_END}\n'
    path.write_text(t, encoding='utf-8')
    print(f'subset ({len(subset)} chars) -> {path.relative_to(ROOT)}')


if __name__ == '__main__':
    subset = build_subset()
    patch(ROOT / 'assets/css/pv-critical-chrome.css', subset)
    patch(ROOT / 'assets/css/pv-critical-home.css', subset)
